### ISSUE TITLE
Buffer used without being explicitly declared

### ISSUE THREAD

**Issue by tneullas** [wanadev/obsidian-file#18]
In 
https://github.com/wanadev/obsidian-file/blob/master/lib/ObsidianProjectFile.js
https://github.com/wanadev/obsidian-file/blob/master/lib/codecs.js

Buffer object is used without being explicitly declared, this cause a "ReferenceError: Buffer is not defined"

**Comment by flozz** [comment]
Fix published as **v3.0.1**
